apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: simpleapp
spec:
  replicas: 3
  selector:
    matchLabels:
      gitlabtraining: server
  template:
    metadata:
      labels:
        gitlabtraining: server
    spec:
      containers:
        - image: <image_location>:v1
          name: server
          ports:
            - containerPort: 3000
              protocol: TCP
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always