apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: frontend
spec:
  type: LoadBalancer
  ports:
    - name: "server"
      port: 3000
      targetPort: 3000
  selector:
    gitlabtraining: server